import * as fs from "node:fs";
import * as path from "node:path";
import { detect } from "./detect.js";

export function runInit(dir: string): void {
  const laxyYmlPath = path.join(dir, ".laxy.yml");
  const workflowDir = path.join(dir, ".github", "workflows");
  const workflowPath = path.join(workflowDir, "laxy-verify.yml");
  const gitignorePath = path.join(dir, ".gitignore");

  if (fs.existsSync(laxyYmlPath)) {
    console.log(".laxy.yml already exists. Skipping. Delete it to regenerate.");
  } else {
    let detectedFramework: string | null = null;
    let detectedPort = 3000;
    try {
      const detected = detect(dir);
      detectedFramework = detected.framework ?? "auto";
      detectedPort = detected.port;
    } catch {
      // Keep defaults when auto-detection fails.
    }

    const ymlContent = `# Generated by laxy-verify --init
# See https://github.com/psungmin24/laxy-verify for full docs
framework: ${detectedFramework}   # auto-detected
port: ${detectedPort}
fail_on: bronze

thresholds:
  performance: 70
  accessibility: 85
  seo: 80
  best_practices: 80
`;
    fs.writeFileSync(laxyYmlPath, ymlContent, "utf-8");
    console.log("Created .laxy.yml");
  }

  if (fs.existsSync(workflowPath)) {
    console.log(".github/workflows/laxy-verify.yml already exists. Skipping.");
  } else {
    fs.mkdirSync(workflowDir, { recursive: true });

    const workflowContent = `name: Laxy Verify
on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  pull-requests: write
  statuses: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psungmin24/laxy-verify@v1
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
`;
    fs.writeFileSync(workflowPath, workflowContent, "utf-8");
    console.log("Created .github/workflows/laxy-verify.yml");
  }

  const gitignoreEntries = [".lighthouseci/", ".laxy-result.json"];
  if (fs.existsSync(gitignorePath)) {
    const existing = fs.readFileSync(gitignorePath, "utf-8");
    const lines = existing.split("\n").map((line) => line.trim());
    const missing = gitignoreEntries.filter((entry) => !lines.includes(entry));
    if (missing.length > 0) {
      fs.appendFileSync(gitignorePath, `${missing.join("\n")}\n`, "utf-8");
      console.log(`Appended to .gitignore: ${missing.join(", ")}`);
    }
  } else {
    fs.writeFileSync(gitignorePath, `${gitignoreEntries.join("\n")}\n`, "utf-8");
    console.log("Created .gitignore");
  }

  console.log("\n  Done. Run 'npx laxy-verify .' to verify your project.");
}
